apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespaces: chat
spec:
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Ensure it matches the container port